name: Publish Plugin (VK - curl)

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download VK binary
              run: |
                  curl -L -o vk \
                    https://github.com/vayload/vayload-kit/releases/download/v0.1.0-alpha/vk-ci-v0.1.0-alpha-x86_64-unknown-linux-gnu
                  chmod +x vk
                  sudo mv vk /usr/local/bin/vk

            - name: Publish plugin
              env:
                  VK_API_TOKEN: ${{ secrets.VK_API_TOKEN }}
                  VK_REGISTRY_URL: ${{ vars.VK_REGISTRY_URL }}
              run: |
                  vk publish

            - name: Success notification
              if: success()
              run: echo "✅ Plugin published successfully!"

            - name: Failure notification
              if: failure()
              run: echo "❌ Plugin publish failed!"

